<?xml version="1.0"?>

<!-- A simple model of the racecar for rviz -->

<!--robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="racecar" -->
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="racecar">
  <xacro:arg name="prefix" default=""/>
  
  <xacro:property name="wheelbase" value="0.3302" />
  <xacro:property name="width" value="0.2032" />
  <xacro:property name="height" value="0.1" />
  <xacro:property name="ground_offset" value="0.04" />
  <xacro:property name="wheel_radius" value="0.0508" />
  <xacro:property name="wheel_length" value="0.0381" />
  <xacro:property name="laser_distance_from_base_link" value="0.275" />
  <xacro:property name="laser_height" value="0.05" />
  <xacro:property name="laser_radius" value="0.026" />

  <material name="black">
    <color rgba="0.2 0.2 0.2 1."/>
  </material>

  <material name="green">
    <color rgba="0.0 1.0 0.0 1.0"/>
  </material>

  <link name="base_link$(arg prefix)">
    <visual>
      <origin xyz="${wheelbase/2} 0 ${ground_offset+height/2}"/>
      <geometry>
        <box size="${wheelbase} ${width} ${height}"/>
      </geometry>
      <material name="green"/>
    </visual>
  </link>

  <joint name="base_to_laser_model$(arg prefix)" type="fixed">
    <parent link="base_link$(arg prefix)"/>
    <child link="laser_model$(arg prefix)"/>
    <origin xyz="${laser_distance_from_base_link} 0 ${ground_offset+height+(laser_height/2)}"/>
  </joint>

  <link name="laser_model$(arg prefix)">
    <visual>
      <geometry>
        <cylinder radius="${laser_radius}" length="${laser_height}"/>
      </geometry>
      <material name="black"/>
    </visual>
  </link>

  <joint name="base_to_back_left_wheel$(arg prefix)" type="fixed">
    <parent link="base_link$(arg prefix)"/>
    <child link="back_left_wheel$(arg prefix)"/>
    <origin xyz="0 ${(wheel_length+width)/2} ${wheel_radius}"/>
  </joint>

  <link name="back_left_wheel$(arg prefix)">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
      <material name="black"/>
      <origin rpy="${pi/2} 0 0"/>
    </visual>
  </link>

  <joint name="base_to_back_right_wheel$(arg prefix)" type="fixed">
    <parent link="base_link$(arg prefix)"/>
    <child link="back_right_wheel$(arg prefix)"/>
    <origin xyz="0 ${-(wheel_length+width)/2} ${wheel_radius}"/>
  </joint>

  <link name="back_right_wheel$(arg prefix)">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
      <material name="black"/>
      <origin rpy="${pi/2} 0 0"/>
    </visual>
  </link>

  <joint name="base_to_front_left_hinge$(arg prefix)" type="fixed">
    <parent link="base_link$(arg prefix)"/>
    <child link="front_left_hinge$(arg prefix)"/>
    <origin xyz="${wheelbase} ${(wheel_length+width)/2} ${wheel_radius}"/>
  </joint>

  <link name="front_left_hinge$(arg prefix)"/>

  <joint name="front_left_hinge_to_wheel$(arg prefix)" type="continuous">
    <parent link="front_left_hinge$(arg prefix)"/>
    <child link="front_left_wheel$(arg prefix)"/>
  </joint>

  <link name="front_left_wheel$(arg prefix)">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
      <material name="black"/>
      <origin rpy="${pi/2} 0 0"/>
    </visual>
  </link>

  <joint name="base_to_front_right_hinge$(arg prefix)" type="fixed">
    <parent link="base_link$(arg prefix)"/>
    <child link="front_right_hinge$(arg prefix)"/>
    <origin xyz="${wheelbase} ${-(wheel_length+width)/2} ${wheel_radius}"/>
  </joint>

  <link name="front_right_hinge$(arg prefix)"/>

  <joint name="front_right_hinge_to_wheel$(arg prefix)" type="continuous">
    <parent link="front_right_hinge$(arg prefix)"/>
    <child link="front_right_wheel$(arg prefix)"/>
  </joint>

  <link name="front_right_wheel$(arg prefix)">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
      <material name="black"/>
      <origin rpy="${pi/2} 0 0"/>
    </visual>
  </link>

</robot>
