nn_aukf:
  ros__parameters:
    basic_ukf_path: "/home/a/racecar_simulator/src/nn_odom/models/real/ukf/basic_ukf_scripted.pt"
    nn_ukf_path: "/home/a/racecar_simulator/src/nn_odom/models/real/ukf/51_loss_0.130225_scripted.pt"

    mu_init: 0.8

    use_gpu: true
    timer_period: 100.0
    odom_topic: "/odom"
    imu_topic: "/imu/data"
    control_topic: "/ackermann_cmd"
    motor_current_topic: "/sensors/core"
