racecar_simulator:
  ros__parameters:
    # General parameters
    simulator_frequency: 200.0          # Hz
    odom_frequency: 50.0                # Hz
    imu_frequency: 100.0                # Hz
    scan_frequency: 40.0                # Hz
    scan_beams: 1080                    # number of beams in the lidar scan
    scan_field_of_view: 4.71238898      # rad (270 deg)
    scan_std_dev: 0.01                  # m (scan noise std dev)
    map_free_threshold: 0.2             # m
    detect_car_mode: false              # detect other cars
    state_noise_mode: false             # add noise to the state
    scan_noise_mode: false              # add noise to the scan

    # Topics & frames (car0)
    drive_topic0: "ackermann_cmd0"
    state_topic0: "state0"
    scan_topic0: "scan0"
    odom_topic0: "odom0"
    collision_topic0: "collision0"
    imu_topic0: "imu0"
    base_frame0: "base_link0"
    scan_frame0: "laser_model0"

    # Vehicle parameters (car0)
    mass0: 3.5                          # kg
    l_f0: 0.17145                       # m  distance from CoM to front axle
    l_r0: 0.17145                       # m  distance from CoM to rear axle
    I_z0: 0.04712                       # kg*m^2 yaw moment of inertia

    # Tire/friction model
    Mu_x0: 0.8
    Mu_y0: 0.8
    B_xf0: 1.5
    C_xf0: 1.5
    D_xf0: 30.0
    B_xr0: 1.5
    C_xr0: 1.5
    D_xr0: 30.0
    B_yf0: 1.5
    C_yf0: 1.5
    D_yf0: 30.0
    B_yr0: 1.5
    C_yr0: 1.5
    D_yr0: 30.0

    # Drivetrain & motor (car0)
    wheel_radius0: 0.05                 # m
    gear_ratio0: 3.846                  # 50/13
    # motor_torque_constant0: 0.00273     # N*m/A
    # power_train_inertia0: 7.0e-5        # kg*m^2 
    # coulomb_friction0: 3.0e-3           # N*m
    # viscous_friction0: 4.0e-6           # N*m*s/rad
    motor_torque_constant0: 0.9
    power_train_inertia0: 0.2
    coulomb_friction0: 0.5
    viscous_friction0: 0.3

    # Limits (car0)
    steer_max0: 0.4                     # rad
    steer_vel_max0: 4.0                 # rad/s
    speed_max0: 10.0                    # m/s
    accel_max0: 40.0                    # m/s^2
    decel_max0: 40.0                    # m/s^2
    jerk_max0: 1000.0                    # m/s^3